dist: trusty
sudo: required
cache:
- apt
env:
  global:
  - REPOSITORY=prpy
  - DISTRIBUTION=https://raw.githubusercontent.com/personalrobotics/pr-rosinstalls/feature/rosdistro/repositories.yml
# Allow Python to find packages installed by apt.
# See: http://docs.travis-ci.com/user/languages/python/#Travis-CI-Uses-Isolated-virtualenvs
language: python
python:
- '2.7'
virtualenv:
  system_site_packages: true
# Install test fixture dependencies.
before_install:
- mkdir -p "${HOME}/workspace/src"
- cd "${HOME}/workspace"
- curl -sSo distribution.yml "${DISTRIBUTION}"
- git clone https://github.com/personalrobotics/pr-cleanroom.git scripts
- ./scripts/internal-setup.sh
install:
- mv "${TRAVIS_BUILD_DIR}" src
- ./scripts/internal-distro.py --workspace=src distribution.yml --repository "${REPOSITORY}"
script:
- ./scripts/internal-build.sh $(./internal-get-packages.py distribution.yml "${REPOSITORY}")
after_script:
- ./scripts/view-all-results.sh test_results
