dist: trusty
sudo: required
env:
  global:
  - REPOSITORY=prpy
# Allow Python to find packages installed by apt.
# See: http://docs.travis-ci.com/user/languages/python/#Travis-CI-Uses-Isolated-virtualenvs
language: python
python:
- '2.7'
virtualenv:
  system_site_packages: true
# Install test fixture dependencies.
before_install:
- git clone https://github.com/personalrobotics/pr-cleanroom.git
- cd pr-cleanroom
- curl -O https://raw.githubusercontent.com/personalrobotics/pr-rosinstalls/feature/rosdistro/repositories.yml
- ./internal-setup.sh
# Checkout this repository and all of its dependencies.
install:
- ./internal-distro.py --workspace=src --repository "${REPOSITORY}" distribution/distribution.yml
# Build the workspace and run tests.
script:
- ./internal-build.sh $(./internal-get-packages.py repositories.yml "${REPOSITORY}")
