sudo: required
dist: trusty
services:
- docker
install:
- git clone https://github.com/personalrobotics/pr-cleanroom.git .
- wget https://raw.githubusercontent.com/personalrobotics/pr-rosinstalls/feature/rosdistro/repositories.yml
script:
- ./run-distro.sh repositories.yml --repository=prpy
