sudo: required
dist: trusty
install:
- export repository='prpy'
- git clone https://github.com/personalrobotics/pr-cleanroom.git
- cd pr-cleanroom
- curl -o https://raw.githubusercontent.com/personalrobotics/pr-rosinstalls/feature/rosdistro/repositories.yml
- ./internal-setup.sh
- ./internal-distro.py --workspace=src --repository ${repository} distribution/distribution.yml
script:
- ./internal-build.sh $(./internal-get-packages.py repositories.yml ${repository})
