pitcher_grasp:
   sample_start: False
   sample_goal: True
   constrain: False
   TSRs:
       - Tw_e: [[0.802, 0., -0.596, 0.199], [-0.5961, 0., -0.8028, 0.2684], [0., 1., 0., 0.1841], [0., 0., 0., 1.]]
         Bw: [[0., 0.],[0., 0.],[-0.01, 0.01],[0., 0.],[0., 0.], [0., 0.]]