pitcher_grasp:
   sample_start: False
   sample_goal: True
   constrain: False
   TSRs:
       - Tw_e: [[0.802, 0., -0.596, 0.199], [-0.5961, 0., -0.8028, 0.2684], [0., 1., 0., 0.1841], [0., 0., 0., 1.]]
         Bw: [[0., 0.],[0., 0.],[-0.01, 0.01],[0., 0.],[0., 0.], [0., 0.]]
pitcher_tilt:
    sample_start: False
    sample_goal: True
    TSRs:
       # spout in pitcher
       - Tw_e: [[-0.7956, 0.6057, 0., -0.0662],[-0.6057, -0.7956, 0., -0.0504],[0., 0., 1., 0.2376], [0., 0., 0., 1.]]
         Bw: [[0., 0.],[0., 0.],[0.0, 0.0],[0., 0.],[-3.14, 3.14], [0., 0.]]
pitcher_pour:
    sample_start: False
    sample_goal: False
    constrain: True
    TSRs:
       # spout in pitcher
       - Tw_e: [[-0.7956, 0.6057, 0., -0.0662],[-0.6057, -0.7956, 0., -0.0504],[0., 0., 1., 0.2376], [0., 0., 0., 1.]]
         Bw: [[0., 0.],[0., 0.],[0.0, 0.0],[0., 0.],[0., 0.],[-3.14, 3.14]]
       # handle in spout
       - Tw_e: [[-0.2770, 0., 0.9605, -0.4041],[0.9601, 0., 0.2777, 0.093],[0., 1., 0., -0.0535],[0., 0., 0., 1.]]
         Bw: [[0., 0.],[0., 0.],[-0.01, 0.01],[0., 0.],[0., 0.], [0., 0.]]